# Generated by Django 6.0.5 on 2026-05-19 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_player", models.IntegerField(default=1)),
                ("turn_number", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("finished", "Finished")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("winner", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("castle", "Castle"), ("house", "House")],
                        max_length=10,
                    ),
                ),
                ("owner", models.IntegerField(blank=True, null=True)),
                ("hp", models.IntegerField(default=20)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildings",
                        to="game.gamesession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Piece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("king", "King"),
                            ("queen", "Queen"),
                            ("rook", "Rook"),
                            ("bishop", "Bishop"),
                            ("knight", "Knight"),
                            ("pawn", "Pawn"),
                        ],
                        max_length=10,
                    ),
                ),
                ("owner", models.IntegerField()),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("hp", models.IntegerField()),
                ("max_hp", models.IntegerField()),
                ("attack", models.IntegerField()),
                ("defense", models.IntegerField()),
                ("move_points", models.IntegerField()),
                ("xp", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                ("has_moved", models.BooleanField(default=False)),
                ("has_attacked", models.BooleanField(default=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="game.gamesession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                (
                    "terrain_type",
                    models.CharField(
                        choices=[
                            ("plains", "Plains"),
                            ("forest", "Forest"),
                            ("mountain", "Mountain"),
                            ("water", "Water"),
                            ("road", "Road"),
                        ],
                        default="plains",
                        max_length=10,
                    ),
                ),
                (
                    "building",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tile",
                        to="game.building",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiles",
                        to="game.gamesession",
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "x", "y")},
            },
        ),
    ]
